name: mha57
services:

  node1:
    image: 57node
    hostname: node1
    build:
      context: ../images/mha/57node/
    volumes:
      - ./node1/etc/my.cnf:/etc/my.cnf
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -sNe \"select 1;\"" ]
      start_period: 20s
      retries: 10
      interval: 10s
      timeout: 10s

  node2:
    image: 57node
    hostname: node2
    build:
      context: ../images/mha/57node/
    volumes:
      - ./node2/etc/my.cnf:/etc/my.cnf
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -sNe \"select 1;\"" ]
      start_period: 20s
      retries: 10
      interval: 10s
      timeout: 10s
    depends_on:
      node1:
        condition: service_healthy

  node3:
    image: 57node
    hostname: node3
    build:
      context: ../images/mha/57node/
    volumes:
      - ./node3/etc/my.cnf:/etc/my.cnf
    privileged: true
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -sNe \"select 1;\"" ]
      start_period: 20s
      retries: 10
      interval: 10s
      timeout: 10s
    depends_on:
      node1:
        condition: service_healthy

  manager:
    image: manager
    hostname: manager
    build:
      context: ../images/mha/manager/
    volumes:
      - ./manager/etc/app1.cnf:/etc/app1.cnf
      - ./manager/usr/lib/systemd/system/mha-app1.service:/usr/lib/systemd/system/mha-app1.service
    privileged: true

  ladder:
    image: ladder:latest
    hostname: ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: ladder:latest
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra

  initer:
    image: ladder:latest
    build:
      context: ../images/ladder/
    volumes:
      - ./initer.d:/initer.d:ro
    entrypoint: /initer-entrypoint.sh
    tty: true
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
