name: mha57
services:

  node1:
    image: 57node
    hostname: node1
    build:
      context: ../images/mha/57node/
    privileged: true

  node2:
    image: 57node
    hostname: node2
    build:
      context: ../images/mha/57node/
    privileged: true

  node3:
    image: 57node
    hostname: node3
    build:
      context: ../images/mha/57node/
    privileged: true

  ladder:
    image: ladder:latest
    hostname: ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: ladder:latest
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra
