services:

  mysql84:
    container_name: mysql84
    image: mysql:8.4
    volumes:
      - ./etc/mysql84-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    profiles:
      - extra

  mysql80:
    container_name: mysql80
    image: mysql:8.0
    volumes:
      - ./etc/mysql80-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    volumes:
      - ./etc/mysql57-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  mysql56:
    container_name: mysql56
    image: mysql:5.6
    volumes:
      - ./etc/mysql56-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  ladder:
    container_name: ladder
    build:
      context: ../images/ladder/
    ports:
      - 30000:22
    tty: true
