services:

  mysql84:
    image: mysql:8.4
    volumes:
      - ./etc/mysql84-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    profiles:
      - extra

  mysql80:
    image: mysql:8.0
    volumes:
      - ./etc/mysql80-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password

  mysql57:
    image: mysql:5.7
    volumes:
      - ./etc/mysql57-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  mysql56:
    image: mysql:5.6
    volumes:
      - ./etc/mysql56-my.cnf:/etc/my.cnf:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  ladder:
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra
