services:

  # RHEL 8,9
  rhel9:
    image: redhat/ubi9-init
    privileged: true

  rhel8:
    image: redhat/ubi8-init
    privileged: true

  # CentOS 6-,7-,8
  centos8:
    image: local/centos8
    build:
      context: ../images/os/centos8/
    privileged: true
    command: /sbin/init

  centos7:
    image: centos:7
    privileged: true
    command: /sbin/init

  centos6:
    image: local/centos6
    build:
      context: ../images/os/centos6/
    privileged: true
    command: /sbin/init

  # SUSE 15
  suse15:
    image: local/suse15
    build:
      context: ../images/os/suse15
    privileged: true

  # OpenSUSE 15
  opensuse15:
    image: local/opensuse15
    build:
      context: ../images/os/opensuse15
    privileged: true

  # Amazon Linux 2,2023
  amazonlinux2023:
    image: local/amazonlinux2023
    build:
      context: ../images/os/amazonlinux2023/
    privileged: true
    command: /sbin/init

  amazonlinux2:
    image: local/amazonlinux2
    build:
      context: ../images/os/amazonlinux2/
    privileged: true
    command: /sbin/init

  # Debian 10,11,12
  debian12:
    image: local/debian12
    build:
      context: ../images/os/debian12/
    privileged: true
    command: /sbin/init

  debian11:
    image: local/debian11
    build:
      context: ../images/os/debian11/
    privileged: true
    command: /sbin/init

  debian10:
    image: local/debian10
    build:
      context: ../images/os/debian10/
    privileged: true
    command: /sbin/init

  # Ubuntu 2004,2204,2404
  ubuntu2404:
    image: local/ubuntu2404
    build:
      context: ../images/os/ubuntu2404/
    privileged: true

  ubuntu2204:
    image: local/ubuntu2204
    build:
      context: ../images/os/ubuntu2204/
    privileged: true

  ubuntu2004:
    image: local/ubuntu2004
    build:
      context: ../images/os/ubuntu2004/
    privileged: true

  # Oracle 8,9

  # Rocky Linux 8,9
  rockylinux9:
    image: local/rockylinux9
    build:
      context: ../images/os/rockylinux9/
    privileged: true

  rockylinux8:
    image: local/rockylinux8
    build:
      context: ../images/os/rockylinux8/
    privileged: true

  # Alma Linux 8,9
  almalinux9:
    image: almalinux:9
    privileged: true
    command: /sbin/init

  almalinux8:
    image: almalinux:8
    privileged: true
    command: /sbin/init

  # Alpine latest
  alpine:
    image: alpine
    privileged: true
    command: /sbin/init

  ladder:
    image: local/ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: local/latest
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra
