name: playground
services:

  mysql90:
    image: mysql:9.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    profiles:
      - extra

  mysql84:
    image: mysql:8.4
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    profiles:
      - extra

  mysql80:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --default-authentication-plugin=mysql_native_password

  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  mysql56:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  mysql55:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --default-authentication-plugin=mysql_native_password
    profiles:
      - extra

  ladder:
    image: local/ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: local/ladder
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra
