name: sn84
services:

  node1:
    image: mysql:8.4
    hostname: node1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  ladder:
    image: ladder:latest
    hostname: ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: ladder:latest
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra
