name: mn56
services:

  node1:
    image: mysql:5.6
    hostname: node1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=1 
      --default-authentication-plugin=mysql_native_password

  node2:
    image: mysql:5.6
    hostname: node2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=2 
      --default-authentication-plugin=mysql_native_password

  node3:
    image: mysql:5.6
    hostname: node3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=3 
      --default-authentication-plugin=mysql_native_password

  ladder:
    image: local/ladder
    hostname: ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: local/ladder
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra

  mysqlsh:
    image: local/mysqlsh
    build:
      context: ../images/mysqlsh/
    tty: true
    profiles:
      - extra
