name: mn84
services:

  node1:
    image: mysql:8.4
    hostname: node1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=1 

  node2:
    image: mysql:8.4
    hostname: node2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=2 

  node3:
    image: mysql:8.4
    hostname: node3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=3 

  ladder:
    image: ladder:latest
    hostname: ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: ladder:latest
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra

  mysqlsh:
    image: mysqlsh:latest
    build:
      context: ../images/mysqlsh/
    tty: true
    profiles:
      - extra
