name: cr57
services:

  node1:
    image: mysql:5.7
    hostname: node1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --log_bin
      --server_id=1 
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -sNe \"select 1;\"" ]
      start_period: 20s
      retries: 10
      interval: 10s
      timeout: 10s

  node2:
    image: mysql:5.7
    hostname: node2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=2 
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -sNe \"select 1;\"" ]
      start_period: 20s
      retries: 10
      interval: 10s
      timeout: 10s
    depends_on:
      node1:
        condition: service_healthy

  node3:
    image: mysql:5.7
    hostname: node3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: |
      --server_id=3 
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -sNe \"select 1;\"" ]
      start_period: 20s
      retries: 10
      interval: 10s
      timeout: 10s
    depends_on:
      node2:
        condition: service_healthy

  ladder:
    image: local/ladder
    hostname: ladder
    build:
      context: ../images/ladder/
    ports:
      - :22
    tty: true

  mysql:
    image: local/ladder
    build:
      context: ../images/ladder/
    entrypoint: /usr/bin/mysql
    tty: true
    profiles:
      - extra

  mysqlsh:
    image: local/mysqlsh
    build:
      context: ../images/mysqlsh/
    tty: true
    profiles:
      - extra

  initer:
    image: local/ladder
    build:
      context: ../images/ladder/
    volumes:
      - ./initer.d:/initer.d:ro
    entrypoint: /initer-entrypoint.sh
    tty: true
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
